"""Exact semigroup certificate for two-saturation of Fano rank profiles.

Together with the exact 78-element Hilbert basis of the triangle cone, this
shows that twice every integral triangle-cone profile is realizable.  The
script only uses profiles with separately verified alternating-net witnesses.
"""

from __future__ import annotations

from collections import deque
from itertools import combinations_with_replacement

from probe_fano_profile_semigroup_holes import (
    LINES,
    known_actual_generators,
    rank_four_atoms,
)


def add(left: tuple[int, ...], right: tuple[int, ...]) -> tuple[int, ...]:
    return tuple(a + b for a, b in zip(left, right))


def main() -> None:
    singleton_jumps = tuple(
        tuple(2 if point == distinguished else 1 for point in range(7))
        for distinguished in range(7)
    )
    line_jumps = tuple(
        tuple(2 if point in line else 1 for point in range(7))
        for line in LINES
    )
    missing = singleton_jumps + line_jumps

    actual = known_actual_generators()
    pair_targets = {add(left, right) for left, right in combinations_with_replacement(missing, 2)}
    indexed_triples = tuple(combinations_with_replacement(range(len(missing)), 3))
    triple_targets = {
        indices: tuple(sum(missing[index][point] for index in indices) for point in range(7))
        for indices in indexed_triples
    }
    good_atoms = rank_four_atoms()
    mixed_targets = {
        (index, good): add(missing[index], good)
        for index in range(len(missing)) for good in good_atoms
    }
    all_targets = pair_targets | set(triple_targets.values()) | set(mixed_targets.values())
    maximum_coordinate = max(max(target) for target in all_targets)
    maximum_sum = max(sum(target) for target in all_targets)
    usable = tuple(
        generator for generator in actual
        if max(generator) <= maximum_coordinate and sum(generator) <= maximum_sum
    )

    zero = (0,) * 7
    reachable = {zero}
    queue = deque([zero])
    while queue:
        current = queue.popleft()
        for generator in usable:
            successor = add(current, generator)
            if max(successor) > maximum_coordinate or sum(successor) > maximum_sum:
                continue
            if successor not in reachable:
                reachable.add(successor)
                queue.append(successor)

    assert pair_targets.issubset(reachable)

    triple_failures = {
        indices for indices, target in triple_targets.items() if target not in reachable
    }
    assert triple_failures == {(index, index, index) for index in range(7)}

    mixed_failures = {
        key for key, target in mixed_targets.items() if target not in reachable
    }
    expected_mixed_failures = {
        (
            distinguished,
            tuple(0 if point in line else 1 for point in range(7)),
        )
        for distinguished in range(7)
        for line in LINES if distinguished not in line
    }
    assert mixed_failures == expected_mixed_failures

    # A transparent decomposition of twice a singleton jump: for a fixed
    # point p, sum the four cut rays whose zero lines avoid p.
    for distinguished, singleton in enumerate(singleton_jumps):
        cuts = tuple(
            tuple(0 if point in line else 1 for point in range(7))
            for line in LINES if distinguished not in line
        )
        assert len(cuts) == 4
        assert tuple(sum(cut[point] for cut in cuts) for point in range(7)) == tuple(
            2 * value for value in singleton
        )

    # Twice every line jump is one of the verified symmetrized 4x4 witnesses.
    for line_jump in line_jumps:
        assert tuple(2 * value for value in line_jump) in actual

    print(
        f"actual_generators={len(actual)} missing_atoms={len(missing)} "
        f"pair_targets={len(pair_targets)} triple_targets={len(triple_targets)} "
        f"mixed_targets={len(mixed_targets)} reachable={len(reachable)}"
    )
    print("PASS: every pair of missing Hilbert atoms is generated by exact witnesses")
    print("PASS: only triple failures are three equal singleton jumps")
    print("PASS: only missing+good failures are singleton plus one avoiding cut ray")
    print("THEOREM_INPUT: twice every integral Fano triangle-cone profile is realizable")


if __name__ == "__main__":
    main()
